### ISSUE TITLE
Errors with whitespace in `triton-docker inspect --format "string"`

### ISSUE THREAD

**Issue by sysaeon** [joyent/triton-docker-cli#14] opened 2017-09-05 21:33 UTC
This tool doesn't seem to like whitespace in the format string, while it works with docker.
```
$ docker inspect --format '{{ .NetworkSettings.IPAddress }}' c2
192.168.128.178
```
```
$ triton-docker inspect --format '{{ .NetworkSettings.IPAddress }}' c2
Template parsing error: template: :1: unexpected unclosed action in command
```
```
$ triton-docker inspect --format '{{.NetworkSettings.IPAddress}}' c2
192.168.128.178
```
Version info:
```
$ triton-docker version
Client:
 Version:      1.12.6
 API version:  1.24
 Go version:   go1.6.4
 Git commit:   78d1802
 Built:        Wed Jan 11 00:23:16 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21
 Go version:   node4.6.1
 Git commit:   ade9dd9
 Built:        Thu Aug  3 17:13:55 2017
 OS/Arch:      solaris/i386
```
```
$ docker version
Client:
 Version:      1.13.1
 API version:  1.24 (downgraded from 1.26)
 Go version:   go1.7.5
 Git commit:   092cba3
 Built:        Wed Feb  8 08:47:51 2017
 OS/Arch:      darwin/amd64

Server:
 Version:      1.9.0
 API version:  1.21 (minimum version )
 Go version:   node4.6.1
 Git commit:   ade9dd9
 Built:        Thu Aug  3 17:13:55 2017
 OS/Arch:      solaris/i386
 Experimental: false
```

**Comment by misterbisson** [comment] 2017-09-06 16:06
[As noted in the readme](https://github.com/joyent/triton-docker-cli#components),`triton-docker` is expected to behave exactly the same as Docker 1.12.6 (because it is Docker 1.12.6).

I'm going to close this as "not a bug," but if you find that `triton-docker` is behaving differently from `docker` 1.12.6, then please reopen or open a new one.

**Closed as completed by misterbisson** 2017-09-06 16:06 UTC
Labels: not a bug
